exclude: |
    (?x)(
        ^data/ |
        ^howl-models |
        ^.github/
    )

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: name-tests-test
-   repo: https://github.com/timothycrosley/isort
    rev: 5.5.4
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        args: ['--line-length=120']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: ['--max-line-length=120', '--extend-ignore=E203']
# TODO: enable the following checks in a separate MR
#-   repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.6.0
#    hooks:
#    -   id: pylint
#        args: ['--max-line-length=120',
#               '--disable=import-error',
#               '--disable=missing-function-docstring',
#               '--disable=missing-class-docstring',
#               '--disable=missing-module-docstring']
# TODO: enable to check for docstring and drop missing-docstring from pylint
#-   repo: https://github.com/pycqa/pydocstyle
#    rev: 6.1.1
#    hooks:
#    -   id: pydocstyle
